import { Project, Experience, Education, Skill, ContactInfo } from '@/types';

export const contactInfo: ContactInfo = {
  email: 'jess.c.zhou@gmail.com',
  linkedin: 'https://linkedin.com/in/jessicaz-',
  github: 'https://github.com/jjcyz',
  instagram: 'https://www.instagram.com/_jessicazhou/',
};

export const projects: Project[] = [
  {
    id: 'real-time-fraud-detection',
    title: 'Real time Fraud Detection System',
    description: 'Full-stack fraud detection system with Java Spring Boot backend and React frontend for real-time transaction monitoring and multi-layered fraud detection.',
    longDescription: 'Developed a comprehensive fraud detection platform featuring 7 detection rules, real-time analysis, MySQL database RESTful API, and Apache Kafka integration for event-driven async processing.',
    image: '/images/ml_paper_pipeline.PNG',
    technologies: ['Java', 'Spring Boot', 'React', 'MySQL', 'Apache Kafka'],
    liveUrl: 'https://github.com/jjcyz/real-time-security',
    iframeUrl: 'https://real-time-security.vercel.app/',
    featured: true,
    category: 'ai',
  },
    {
    id: 'destination-ai',
    title: 'Destination AI: AI-Powered Route Planning',
    description: 'An intelligent route planning application that uses AI to optimize travel routes, suggest efficient paths, and provide real-time navigation recommendations for seamless journey planning.',
    longDescription: 'Developed a sophisticated route planning platform leveraging AI algorithms to analyze multiple factors including traffic patterns, distance optimization, and user preferences. Features intelligent pathfinding, real-time route adjustments, and personalized recommendations for optimal travel experiences.',
    image: '/images/placeholder.svg',
    technologies: ['Javascript', 'React', 'Next.js', 'Google Maps API', 'TransLink API', 'OpenWeatherMap API'],
    liveUrl: 'https://destination-ai.vercel.app/',
    iframeUrl: 'https://destination-ai.vercel.app/',
    featured: true,
    category: 'ai',
  },
  {
    id: 'ubc-bolt-website',
    title: 'UBC BOLT Website',
    description: 'Official website for UBC Data Analytics (BOLT) student organization, featuring modern design, event management, and member resources for 200+ data science enthusiasts.',
    longDescription: 'Designed and developed the official website for UBC\'s premier data analytics student organization. Features responsive design, event calendar integration, member resources, and seamless user experience to support the club\'s 200+ members and various data science initiatives.',
    image: '/images/placeholder.svg',
    technologies: ['JavaScript', 'React', 'Next.js', 'Tailwind CSS', 'Supabase', 'Google API'],
    liveUrl: 'https://boltubc.com/',
    iframeUrl: 'https://boltubc.com/',
    featured: true,
    category: 'web',
  },
  {
    id: 'ubc-ux-hub-website',
    title: 'UBC UX Hub Website',
    description: 'Official website for UBC UX Hub, UBC\'s first and largest UX design club since 2017, featuring modern design, event showcases, team profiles, and community resources.',
    longDescription: 'Designed and developed the official website for UBC\'s premier user experience design club. Features responsive design, event management, team member profiles, newsletter integration, and seamless user experience to support the club\'s mission of empowering the next generation of UX designers through hands-on learning and creative collaboration.',
    image: '/images/placeholder.svg',
    technologies: ['JavaScript', 'React', 'Next.js', 'Tailwind CSS'],
    liveUrl: 'https://www.ubcuxhub.ca/',
    iframeUrl: 'https://www.ubcuxhub.ca/',
    featured: true,
    category: 'web',
  },
  {
    id: 'arcsphere',
    title: 'ArcSphere: AI Agents Powered By Groq',
    description: 'Developed a modern web application using Groq\'s LLaMA 3 70B model, featuring a chat interface for users to interact with AI agents.',
    longDescription: 'Built a sophisticated AI chat application leveraging Groq\'s lightning-fast inference API. Implemented custom system prompts to define specific AI agent capabilities, created a responsive React interface with real-time messaging, and integrated advanced error handling for robust user experience.',
    image: '/images/placeholder.svg',
    technologies: ['JavaScript', 'ReactJS', 'Vite', 'NodeJS', 'Groq'],
    liveUrl: 'https://arcsphere.vercel.app/',
    iframeUrl: 'https://arcsphere.vercel.app/',
    featured: true,
    category: 'ai',
  },
  {
    id: 'chatroom',
    title: 'Client-Server Chatroom Application',
    description: 'Developed a multi-threaded chat server in C++ using socket programming, supporting concurrent user connections with real-time message broadcasting.',
    longDescription: 'Implemented a high-performance chat server with sub-100ms message delivery latency. Features include concurrent user management, real-time message broadcasting, robust error handling, and efficient memory management for scalable communication.',
    image: '/images/placeholder.svg',
    technologies: ['C++', 'Socket Programming', 'Multi-threading'],
    githubUrl: 'https://github.com/jjcyz/client-server-chat',
    featured: true,
    category: 'systems',
  },
  {
    id: 'blood-vessel-segmentation',
    title: 'Blood Vessel Segmentation',
    description: 'Developed a 3D U-Net architecture for precise pixel-wise classification of vasculature structures, automating kidney segmentation and reducing manual processing time by 85%.',
    longDescription: 'Created an innovative two-step training pipeline combining supervised pretraining with denoising techniques. Built an end-to-end pipeline processing TIFF scans and generating 3D segmentation masks, achieving state-of-the-art results in medical image analysis.',
    image: '/images/ml_paper_pipeline.PNG',
    technologies: ['Python', 'Tensorflow', 'PyTorch', 'Machine Learning'],
    paperUrl: 'https://openreview.net/forum?id=kl3kxvM4Nn#discussion',
    featured: true,
    category: 'research',
  },
  {
    id: 'vae-comparison',
    title: 'Variational Autoencoder (VAE) Comparison',
    description: 'Implemented and compared Bernoulli and Gaussian VAEs using PyTorch, achieving 90% reconstruction accuracy on the MNIST dataset with a compact 40-dimensional latent space.',
    longDescription: 'Built comprehensive visualization pipeline generating 6 different analysis outputs including loss comparisons and reconstruction quality metrics. Optimized model training through systematic hyperparameter tuning and implemented advanced data preprocessing techniques.',
    image: '/images/placeholder.svg',
    technologies: ['Python', 'PyTorch', 'Data Visualization'],
    githubUrl: 'https://github.com/jjcyz/bernoulli_gaussian_vae',
    featured: true,
    category: 'research',
  },
];

export const experiences: Experience[] = [
  {
    id: 'campus-partner-perplexity',
    title: 'Campus Partner',
    company: 'Perplexity AI',
    location: 'Vancouver, CA',
    startDate: '2025-09',
    endDate: 'present',
    description: [
      'Represent Perplexity AI on campus and promote AI-powered search technology to students',
      'Organize and host workshops and events to demonstrate Perplexity\'s capabilities in research and academic work',
      'Build relationships with academic departments and student organizations to increase AI adoption',
    ],
    technologies: ['AI', 'Community Building', 'Event Management'],
  },
  {
    id: 'vp-technology-bolt',
    title: 'VP of Technology',
    company: 'UBC Data Analytics (BOLT)',
    location: 'Vancouver, CA',
    startDate: '2025-09',
    endDate: 'present',
    description: [
      'Lead the technical direction and strategy for UBC\'s premier data analytics student organization',
      'Oversee development of data science projects and technical workshops for 200+ members',
      'Manage technical infrastructure and ensure smooth operation of club events and competitions',
      'Mentor junior members in data analytics and technical project development',
    ],
    technologies: ['Data Analytics', 'Python', 'Leadership', 'JavaScript', 'React, Atlassian Suite'],
  },
  {
    id: 'software-developer-ux-hub',
    title: 'Software Developer',
    company: 'UBC UX Hub',
    location: 'Vancouver, CA',
    startDate: '2025-09',
    endDate: 'present',
    description: [
      'Develop user-centered web applications and digital tools for the UBC UX Hub community',
      'Collaborate with UX designers to implement responsive and accessible user interfaces',
      'Build and maintain the organization\'s website and internal tools using modern web technologies',
    ],
    technologies: ['JavaScript', 'React', 'Node.js', 'UX/UI Design', 'Web Development'],
  },
  {
    id: 'events-logistics-lead-gdsc',
    title: 'Events and Logistics Lead',
    company: 'Google Developer Student Club',
    location: 'Vancouver, CA',
    startDate: '2025-09',
    endDate: 'present',
    description: [
      'Plan and coordinate technical workshops, hackathons, and developer events for 300+ student members',
      'Manage event logistics including venue booking, speaker coordination, and resource allocation',
      'Collaborate with Google and industry partners to bring technology workshops to campus',
      'Lead a team of volunteers to ensure smooth execution of developer events and competitions',
    ],
    technologies: ['Event Management', 'Project Management', 'Leadership', 'Community Building'],
  },
  {
    id: 'software-engineer-intern',
    title: 'Software Engineer Intern',
    company: 'Polymuse',
    location: 'Vancouver, CA',
    startDate: '2025-05',
    endDate: '2025-09',
    description: [
      'Early startup work in AR and AI - coming soon ',
    ],
    technologies: ['JavaScript', 'React', 'Google Cloud Platform', 'Firebase'],
  },
  {
    id: 'researcher-blood-vessel',
    title: 'Research',
    company: 'Tsinghua University',
    location: 'Beijing, CN',
    startDate: '2024-09',
    endDate: '2025-01',
    description: [
      'Developed a 3D U-Net architecture for precise pixel-wise classification of vasculature structures',
      'Implemented an innovative two-step training pipeline with supervised pretraining and denoising techniques',
      'Built an end-to-end pipeline processing TIFF scans and generating 3D segmentation masks',
    ],
    technologies: ['Python', 'Tensorflow', 'PyTorch', 'Machine Learning'],
  },
];

export const education: Education[] = [
  {
    id: 'ubc-bucs',
    institution: 'University of British Columbia',
    degree: 'Bachelors in Computer Science & Business',
    location: 'Vancouver, CA',
    startDate: '2022-09',
    endDate: '2026-04',
  },
  {
    id: 'tsinghua-exchange',
    institution: 'Tsinghua University',
    degree: 'Exchange Studies',
    location: 'Beijing, CN',
    startDate: '2024-02',
    endDate: '2025-01',
  },
];

export const skills: Skill[] = [
  // Frontend
  { name: 'JavaScript', category: 'frontend', description: 'Dynamic language for interactive web experiences.' },
  { name: 'TypeScript', category: 'frontend', description: 'Typed JavaScript for safer, scalable code.' },
  { name: 'ReactJS', category: 'frontend', description: 'For building fast, interactive UIs.' },
  { name: 'Next.js', category: 'frontend', description: 'React framework with routing & SSR.' },
  { name: 'TailwindCSS', category: 'frontend', description: 'Utility-first CSS for rapid UI development.' },

  // Backend
  { name: 'Python', category: 'backend', description: 'Versatile language for data science & APIs.' },
  { name: 'Java', category: 'backend', description: 'Enterprise-grade backend development.' },
  { name: 'NodeJS', category: 'backend', description: 'JavaScript runtime for servers.' },
  { name: 'MySQL', category: 'backend', description: 'Reliable relational database management.' },
  { name: 'MongoDB', category: 'backend', description: 'Flexible NoSQL database system.' },
  { name: 'Supabase', category: 'backend', description: 'Open-source Firebase alternative.' },
  { name: 'PyTorch', category: 'backend', description: 'Deep learning framework for ML models.' },
  { name: 'TensorFlow', category: 'backend', description: 'End-to-end machine learning platform.' },
  { name: 'C/C++', category: 'backend', description: 'Systems programming and performance-critical apps.' },

  // Tools & DevOps
  { name: 'Git & GitHub', category: 'tools', description: 'Version control and collaboration.' },
  { name: 'Docker', category: 'tools', description: 'Containers for isolated environments.' },
  { name: 'AWS', category: 'tools', description: 'Cloud infrastructure and services.' },
  { name: 'GCP', category: 'tools', description: 'Google Cloud Platform for scalable apps.' },
  { name: 'Jira', category: 'tools', description: 'Project management and issue tracking.' },
  { name: 'Confluence', category: 'tools', description: 'Team collaboration and documentation.' },

  // Design & Workflow
  { name: 'Github Actions', category: 'design', description: 'CI/CD automation and workflow orchestration.' },
];
