import { Project, Experience, Education, Skill, ContactInfo } from '@/types';

export const contactInfo: ContactInfo = {
  email: 'jess.c.zhou@gmail.com',
  linkedin: 'https://linkedin.com/in/jessicaz-',
  github: 'https://github.com/jjcyz',
  instagram: 'https://www.instagram.com/_jessicazhou/',
};

export const projects: Project[] = [
  {
    id: 'rehabify',
    title: 'Rehabify',
    description: '🏆 nwHacks 2026 Hackathon 1st/631. An AI-powered physical therapy coaching app that uses computer vision and voice AI to monitor exercise form and deliver real-time corrections.',
    image: '/images/placeholder.svg',
    technologies: ['Next.js', 'React', 'MediaPipe', 'Neon PostgreSQL', 'Vapi', 'Deepgram STT', 'Gemini', 'ElevenLabs TTS'],
    websiteUrl: 'https://rehabify.tech',
    githubUrl: 'https://github.com/obro79/Rehabify',
    devpostUrl: 'https://devpost.com/software/rehabify-y2f5mu',
    featured: true,
  },
  {
    id: 'transit-brain',
    title: 'TransitBrain',
    description: 'Real-time operations dashboard for TransLink\'s bus fleet, built to support the transition to battery-electric buses. Ingests live GTFS Realtime feeds, tracks every active bus on a full-screen map, and layers electric bus energy telemetry on top of operational data.',
    image: '/images/placeholder.svg',
    technologies: ['Next.js', 'TypeScript', 'Mapbox GL JS', 'Zustand', 'Tailwind CSS', 'GTFS Realtime', 'Framer Motion'],
    githubUrl: 'https://github.com/jjcyz/transit-brain',
    videoUrl: 'https://youtu.be/hWjZ6eKfDSw',
    featured: true,
  },
  {
    id: 'wealthos',
    title: 'WealthOS',
    description: 'A full-stack financial planning dashboard that uses Monte Carlo simulation, macro regime detection, and human-in-the-loop approval to model retirement outcomes and run what-if scenarios.',
    image: '/images/placeholder.svg',
    technologies: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Recharts', 'FastAPI', 'Pydantic', 'NumPy', 'SciPy'],
    websiteUrl: 'https://wealthos-flax.vercel.app',
    githubUrl: 'https://github.com/jjcyz/wealthos',
    featured: true,
  },
  {
    id: 'real-time-fraud-detection',
    title: 'Real-Time Fraud Detection System',
    description: 'Full-stack fraud detection system with Java Spring Boot backend and React frontend for real-time transaction monitoring and multi-layered fraud detection.',
    image: '/images/ml_paper_pipeline.PNG',
    technologies: ['Java', 'Spring Boot', 'React', 'MySQL', 'Apache Kafka'],
    websiteUrl: 'https://real-time-security.vercel.app/',
    githubUrl: 'https://github.com/jjcyz/real-time-security',
    featured: true,
  },
  {
    id: 'destination-ai',
    title: 'Destination AI',
    description: 'An intelligent route planning application that uses AI to optimize travel routes, suggest efficient paths, and provide real-time navigation recommendations.',
    image: '/images/placeholder.svg',
    technologies: ['JavaScript', 'React', 'Next.js', 'Google Maps API', 'TransLink API', 'OpenWeatherMap API'],
    websiteUrl: 'https://destination-ai.vercel.app/',
    githubUrl: 'https://github.com/jjcyz/destination.ai',
    featured: true,
  },
  {
    id: 'aerohub',
    title: 'AeroHub',
    description: 'An aviation management dashboard for airport operations, featuring flight search, booking management, fleet tracking, and passenger administration. This project started when I was in my 2nd year of university, but has continued to develop from time to time.',
    image: '/images/placeholder.svg',
    technologies: ['Java', 'JavaScript', 'React', 'Next.js', 'Tailwind CSS'],
    websiteUrl: 'https://airport-management-system-alpha.vercel.app/',
    githubUrl: 'https://github.com/jjcyz/airport-management-system',
    featured: true,
  },
  {
    id: 'ubc-bolt-website',
    title: 'UBC BOLT Website',
    description: 'Official website for UBC Data Analytics (BOLT) student organization, featuring modern design, event management, and member resources for 200+ data science enthusiasts.',
    image: '/images/placeholder.svg',
    technologies: ['JavaScript', 'React', 'Next.js', 'Tailwind CSS', 'Supabase', 'Google API'],
    websiteUrl: 'https://boltubc.com/',
    featured: true,
  },
  {
    id: 'ubc-ux-hub-website',
    title: 'UBC UX Hub Website',
    description: 'Official website for UBC UX Hub, UBC\'s first and largest UX design club since 2017, featuring modern design, event showcases, team profiles, and community resources.',
    image: '/images/placeholder.svg',
    technologies: ['JavaScript', 'React', 'Next.js', 'Tailwind CSS'],
    websiteUrl: 'https://www.ubcuxhub.ca/',
    featured: true,
  },
  {
    id: 'arcsphere',
    title: 'ArcSphere',
    description: 'A modern web application using Groq\'s LLaMA 3 70B model, featuring a chat interface for users to interact with AI agents.',
    image: '/images/placeholder.svg',
    technologies: ['JavaScript', 'React', 'Vite', 'Node.js', 'Groq'],
    websiteUrl: 'https://arcsphere.vercel.app/',
    githubUrl: 'https://github.com/jjcyz/arcsphere',
    featured: true,
  },
  {
    id: 'chatroom',
    title: 'Client-Server Chatroom',
    description: 'A multi-threaded chat server in C++ using websockets, supporting concurrent user connections with real-time message broadcasting.',
    image: '/images/placeholder.svg',
    technologies: ['C++', 'CMake', 'OpenSSL', 'React', 'Typescript', 'Node.js'],
    websiteUrl: 'https://client-server-chat.vercel.app/',
    githubUrl: 'https://github.com/jjcyz/client-server-chat',
    featured: true,
  },
  {
    id: 'blood-vessel-segmentation',
    title: 'Blood Vessel Segmentation',
    description: 'A 3D U-Net architecture for precise pixel-wise classification of vasculature structures, automating kidney segmentation and reducing manual processing time by 85%.',
    image: '/images/ml_paper_pipeline.PNG',
    technologies: ['Python', 'TensorFlow', 'PyTorch', 'Machine Learning'],
    websiteUrl: 'https://openreview.net/forum?id=kl3kxvM4Nn#discussion',
    paperUrl: 'https://openreview.net/forum?id=kl3kxvM4Nn#discussion',
    featured: true,
  },
  {
    id: 'vae-comparison',
    title: 'VAE Comparison',
    description: 'Implemented and compared Bernoulli and Gaussian VAEs using PyTorch, achieving 90% reconstruction accuracy on MNIST with a compact 40-dimensional latent space.',
    image: '/images/placeholder.svg',
    technologies: ['Python', 'PyTorch', 'Data Visualization'],
    githubUrl: 'https://github.com/jjcyz/bernoulli_gaussian_vae',
    featured: true,
  },
];

export const experiences: Experience[] = [
  {
    id: 'campus-partner-perplexity',
    title: 'Campus Partner',
    company: 'Perplexity AI',
    location: 'Vancouver, CA',
    startDate: '2025-09',
    endDate: 'present',
    description: [
      'Represent Perplexity AI to build relationships with academic departments and student organizations to increase AI adoption',
      'Organize and host workshops and events to demonstrate Perplexity\'s capabilities in research and academic work',
    ],
    technologies: ['AI', 'Community Building', 'Event Management'],
  },
  {
    id: 'vp-technology-bolt',
    title: 'VP of Technology',
    company: 'UBC Data Analytics (BOLT)',
    location: 'Vancouver, CA',
    startDate: '2025-09',
    endDate: 'present',
    description: [
      'Lead the technical direction and strategy for UBC\'s data analytics student organization',
      'Manage technical infrastructure and ensure software projects meet the operations for events and competitions',
    ],
    technologies: ['Data Analytics', 'Python', 'Leadership', 'JavaScript', 'React', 'Jira', 'Confluence'],
  },
  {
    id: 'software-developer-ux-hub',
    title: 'Software Developer',
    company: 'UBC UX Design Club (UXHub)',
    location: 'Vancouver, CA',
    startDate: '2025-09',
    endDate: 'present',
    description: [
      'Develop user-centered web applications and digital tools for the UBC UX Hub community',
      'Collaborate with UX designers to implement responsive and accessible user interfaces',
    ],
    technologies: ['JavaScript', 'React', 'Node.js', 'UX/UI Design', 'Web Development'],
  },
  {
    id: 'events-logistics-lead-gdsc',
    title: 'Events and Logistics Lead',
    company: 'Google Developer Student Club (GDSC)',
    location: 'Vancouver, CA',
    startDate: '2025-09',
    endDate: 'present',
    description: [
      'Plan and coordinate technical workshops, hackathons, and developer events for 300+ student members',
      'Collaborate with Google and industry partners to bring technology workshops to campus',
    ],
    technologies: ['Leadership', 'Community Building', 'Event Management', 'Project Management'],
  },
  {
    id: 'software-engineer-intern',
    title: 'Software Engineer Intern',
    company: 'Polymuse',
    location: 'Vancouver, CA',
    startDate: '2025-05',
    endDate: '2025-09',
    description: [
      'Early startup in VR/AR. Worked on a developing a product called ProductShot',
      'Worked on the Web Development for the product, fixing code, and shipping features fast.',
    ],
    technologies: ['JavaScript', 'React', 'Google Cloud Platform', 'Firebase'],
  },
  {
    id: 'researcher-blood-vessel',
    title: 'Research',
    company: 'Tsinghua University',
    location: 'Beijing, CN',
    startDate: '2024-09',
    endDate: '2025-01',
    description: [
      'Developed a 3D U-Net architecture for precise pixel-wise classification of vasculature structures',
      'Implemented an innovative two-step training pipeline with supervised pretraining and denoising techniques',
    ],
    technologies: ['Python', 'Tensorflow', 'PyTorch', 'Machine Learning'],
  },
];

export const education: Education[] = [
  {
    id: 'ubc-bucs',
    institution: 'University of British Columbia',
    degree: 'Bachelors in Computer Science & Business',
    location: 'Vancouver, CA',
    startDate: '2022-09',
    endDate: '2026-04',
  },
  {
    id: 'tsinghua-exchange',
    institution: 'Tsinghua University',
    degree: 'Exchange Studies',
    location: 'Beijing, CN',
    startDate: '2024-02',
    endDate: '2025-01',
  },
];

export const skills: Skill[] = [
  // Frontend
  { name: 'JavaScript', category: 'frontend', description: 'Dynamic language for interactive web experiences.' },
  { name: 'TypeScript', category: 'frontend', description: 'Typed JavaScript for safer, scalable code.' },
  { name: 'ReactJS', category: 'frontend', description: 'For building fast, interactive UIs.' },
  { name: 'Next.js', category: 'frontend', description: 'React framework with routing & SSR.' },
  { name: 'TailwindCSS', category: 'frontend', description: 'Utility-first CSS for rapid UI development.' },

  // Backend
  { name: 'Python', category: 'backend', description: 'Versatile language for data science & APIs.' },
  { name: 'Java', category: 'backend', description: 'Enterprise-grade backend development.' },
  { name: 'NodeJS', category: 'backend', description: 'JavaScript runtime for servers.' },
  { name: 'MySQL', category: 'backend', description: 'Reliable relational database management.' },
  { name: 'MongoDB', category: 'backend', description: 'Flexible NoSQL database system.' },
  { name: 'Supabase', category: 'backend', description: 'Open-source Firebase alternative.' },
  { name: 'PyTorch', category: 'backend', description: 'Deep learning framework for ML models.' },
  { name: 'TensorFlow', category: 'backend', description: 'End-to-end machine learning platform.' },
  { name: 'C/C++', category: 'backend', description: 'Systems programming and performance-critical apps.' },

  // Tools & DevOps
  { name: 'Git & GitHub', category: 'tools', description: 'Version control and CI/CD with GitHub Actions.' },
  { name: 'Docker', category: 'tools', description: 'Containers for isolated environments.' },
  { name: 'GCP', category: 'tools', description: 'Google Cloud Platform for scalable apps.' },
];
